#!/bin/sh

# Astyle pre-commit hook - Version 2.0 (By Ramon Fried and Yossi Segev)
# This file should be placed under .git/hooks and should have executables permissions
# Things to change (if you want):
# 1. The Astyle settings (it no longer takes it from the default)
# 2. The files the scripts operates upon (currently only C/C++ source / header files)

DATE=$(date +"%Y-%m-%d_%H:%M:%S")
BACKUPDIR="../formatbackup/$DATE"
INDENTER=$(which uncrustify)

test -x $INDENTER || { echo "Did not find $INDENTER, please install it before continuing." && exit 1; }

# Alter this line to change configuration
if [ -z ${UNCRUSTIFY_CONFIG+x} ]; then
        INDENTER_PARAMETERS="-c .git/hooks/uncrustify.cfg --no-backup"
else
        INDENTER_PARAMETERS="--no-backup"
fi

if git rev-parse --verify HEAD >/dev/null 2>&1; then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$(git config hooks.allownonascii)

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
        # Note that the use of brackets around a tr range is ok here, (it's
        # even required, for portability to Solaris 10's /usr/bin/tr), since
        # the square bracket bytes happen to fall in the designated range.
        test "$(git diff --cached --name-only --diff-filter=A -z $against |
          LC_ALL=C tr -d '[ -~]\0')"
then
        echo "Error: Attempt to add a non-ascii file name."
        echo
        echo "This can cause problems if you want to work"
        echo "with people on other platforms."
        echo
        echo "To be portable it is advisable to rename the file ..."
        echo
        echo "If you know what you are doing you can disable this"
        echo "check using:"
        echo
        echo "  git config hooks.allownonascii true"
        echo
        exit 1
fi

mkdir -p ${BACKUPDIR}
files=$(git-diff-index --diff-filter=ACMR --name-only -r --cached $against -- | grep '^ipSrc\|^ipheaders' | grep '\.c$\|\.cpp$\|\.hpp$\|\.h$')
for file in $files; do
        x=$(echo $file)
        if test "x$x" != "x"; then
                cp --parents $file ${BACKUPDIR}
                # Remove trailing spaces
                sed -i 's/[[:space:]]*$//' $file
        $INDENTER ${INDENTER_PARAMETERS} $file
                git add $file
        fi
done
